Docs for Start
solidjs/solid-docs-next pull request #118
Opened 2022-07-30 11:34 UTC by nksaraf

2022-07-30 18:32 UTC, boehs requested changes

2022-07-30 18:32 UTC, boehs commented on content/start/core-concepts/head-and-metadata.mdx
> +Normally when we are building UIs for our apps, we are dealing with DOM elements that are going to be rendered in the `body` of the `document`. But there are cases where we want to customize what's g
I think this is cleaner?
```suggestion
When we are building UIs for our apps, we are normally dealing with DOM elements that are going to be rendered in the `body` of the `document`. But there are cases where we want to customize what's going to be rendered in the `head` of the `document`. The common elements used in the `head` are:
```

2022-07-30 18:32 UTC, boehs commented on content/start/core-concepts/head-and-metadata.mdx
> -### Use `solid-meta` inside component tree
Is it correct to say `solid-meta` when we are really importing from `solid-start`?

2022-07-30 18:32 UTC, boehs commented on content/start/core-concepts/head-and-metadata.mdx
> +- `link`: Adds assets like stylesheets or scripts for the browser to load for the page
We don't add scripts via links

```suggestion
- `link`: Adds assets like stylesheets for the browser to load for the page
```

2022-07-30 18:32 UTC, boehs commented on content/start/core-concepts/head-and-metadata.mdx
> +In SolidStart, we ship with actual components representing these tags. So: `title` -> `Title`, `meta` -> `Meta`, etc. They can be used, not only as children of `Head` in `root.tsx`, but anywhere in y
```suggestion
SolidStart, has actual components that represent these tags. So: `title` -> `Title`, `meta` -> `Meta`, etc. They can be used, not only as children of `Head` in `root.tsx`, but anywhere in your app, even deep in your component tree. Powered by `@solidjs/meta`, we can interpret these tags and update the `document.head` appropriately.
```

2022-07-30 18:32 UTC, boehs commented on content/start/core-concepts/head-and-metadata.mdx
> +  ...
This isn't a good idea, at least show the head related imports

2022-07-30 18:32 UTC, boehs commented on content/start/core-concepts/head-and-metadata.mdx
> +You can create custom components that wrap `Title` to add a site-specific prefix to all the titles, eg.
Awesome!

2022-07-30 18:32 UTC, boehs commented on content/start/core-concepts/head-and-metadata.mdx
> +  ...
Again, show the meta related imports

2022-07-30 18:32 UTC, boehs commented on content/start/core-concepts/routing-and-pages.mdx
> +Under the hood, SolidStart is able to traverse this directory structure, automatically collect all the routes, and give you the `<FileRoutes />` component. You can use this component to specify your
Good catch!

2022-07-30 18:32 UTC, boehs commented on content/start/core-concepts/routing-and-pages.mdx
> +} from "solid-start";
Thank you for showing imports!

2022-07-30 18:32 UTC, boehs commented on content/start/core-concepts/routing-and-pages.mdx
> +```ts
Not everything is typescript man

2022-07-30 18:33 UTC, boehs commented
Aside from the above changes, this looks good. One other note is that these docs are for a version of solid-start not even *released* yet so like probably wait till .96 before merging

2022-08-01 23:11 UTC, boehs requested changes
I assume this docs is not "finished"

2022-08-01 23:11 UTC, boehs commented on content/start/core-concepts/resource-routes.mdx
> +import { json } from "@remix-run/node"; // or cloudflare/deno
Copy paste????

2022-08-01 23:11 UTC, boehs commented on content/start/core-concepts/resource-routes.mdx
> +};
The text and example are in conflict

2022-08-01 23:11 UTC, boehs commented on content/start/core-concepts/resource-routes.mdx
> +To handle `POST`, `PUT`, `PATCH` or `DELETE` requests export an appropriately named function function:
```suggestion
To handle `POST`, `PUT`, `PATCH` or `DELETE` requests export an appropriately named function:
```

2022-08-01 23:11 UTC, boehs commented on content/start/core-concepts/resource-routes.mdx
> +There's a subtle detail to be aware of when linking to resource routes. You need to link to it with `<Link reloadDocument>` or a plain `<a href>`. If you link to it with a normal `<NavLink href="repo
```suggestion
There's a subtle detail to be aware of when linking to resource routes. You need to link to it with `<Link reloadDocument>` or a plain `<a href>`. If you link to it with a normal `<NavLink href="report.pdf">` without `rel="external"`, then the resource route will be treated as a UI route and SolidStart will try to do client-side navigation to that page.
```

2022-08-01 23:11 UTC, boehs commented on content/start/core-concepts/resource-routes.mdx
> +- JSON API for a mobile app that reuses server-side code with the Remix UI
Another copy paste

2022-08-07 00:11 UTC, Jutanium commented
@nksaraf let's combine this branch and #121

2022-08-07 16:00 UTC, merged

2022-08-07 16:29 UTC, boehs commented
Did you really mean to merge this into main?

2022-08-07 16:46 UTC, Jutanium commented
@boehs I merged it into another branch, made a bunch of changes, and merged into main