Fixed duplicate copy button issue
solidjs/solid-docs-next pull request #256
Opened 2023-06-24 05:31 UTC by JasonHassold

The copy button is duplicated for the light and dark themes, but the copy button was not inside the `<pre>` element which is what has the theme class applied to hide each theme version when it's not needed. 

![image](https://github.com/solidjs/solid-docs-next/assets/25469167/1cb92ce5-2aed-45cd-a644-679089c28122)

![Image 2023-06-24 at 1 31 08 AM](https://github.com/solidjs/solid-docs-next/assets/25469167/5fd180d9-d4d6-4afb-aeff-2ba9653dd40f)

2023-07-15 13:35 UTC, michaelessiet requested changes
Hi Jason, I just tested your PR and I noticed that when the code snippet scrolls horizontally that the copy button doesn't remain fixed. Is there a way for you to make the copy button fixed?

2023-07-15 15:15 UTC, JasonHassold commented
Hey Michael, good catch, I'm working on a fix now!

2023-07-15 15:35 UTC, JasonHassold commented
@michaelessiet just pushed a fix for the issue, please take another look when you get a chance and let me know if there is anything else

2023-07-16 13:41 UTC, michaelessiet approved these changes

2023-07-16 13:41 UTC, merged