docs: Added Flightcontrol Deployment Option
solidjs/solid-docs-next pull request #265
Opened 2023-07-12 21:20 UTC by ModupeD

Flightcontrol fully automates your deployments to Amazon Web Services (AWS)

2023-07-13 13:45 UTC, flybayer approved these changes

2023-07-15 12:44 UTC, michaelessiet commented
Great, PR. Please can you add a few images to the instructions under the Dashboard section to make it a bit easier for visual learners to follow

2023-07-20 13:20 UTC, ModupeD commented
@michaelessiet I have added the images

2023-07-20 15:11 UTC, michaelessiet commented
> @michaelessiet I have added the images

Thanks Modupe, I'll make sure to merge it in this weekend

2023-07-21 17:58 UTC, CBID2 commented on content/guides/how-to-guides/deployment/deploying-to-flightcontrol.mdx
> +Here we're going to use [Flightcontrol](https://www.flightcontrol.dev/?ref=solid) to deploy our Solid project.
[Typo]
```suggestion
Here, we're going to use [Flightcontrol](https://www.flightcontrol.dev/?ref=solid) to deploy our Solid project.
```

2023-07-21 18:02 UTC, CBID2 requested changes
Hi @ModupeD! :) This is off to a great start! :) I just pointed out some typos and other things to consider revising! :)

2023-07-22 12:37 UTC, merged