Fix named export example in basics.mdx
solidjs/solid-docs-next pull request #546
Opened 2024-02-27 14:58 UTC by vincentfretin

For named export, you don't need to use export on both the function and on an object, it's one or the other.

2024-02-27 19:45 UTC, LadyBluenotes requested changes

2024-02-27 19:45 UTC, LadyBluenotes commented on src/routes/concepts/components/basics.mdx
> +}
```suggestion
```typescript
export function MyComponent() {
	return <div>Hello World</div>
}

// or

function MyComponent() {
	return <div>Hello World</div>
}
```

2024-02-28 13:04 UTC, vincentfretin commented
I just accepted your changes @LadyBluenotes, good to merge.
Thanks you for your work and the other persons on the documentation. This looks great! I read it all yesterday, I even learn some new things about the Dynamic and Index components, some store api I didn't know yet.
I only found some minor things to fix, I won't spam you further, I'm done :D

2024-02-28 16:38 UTC, atilafassina approved these changes

2024-02-28 17:55 UTC, LadyBluenotes approved these changes

2024-02-28 17:56 UTC, merged