feat: add solid meta docs
solidjs/solid-docs-next pull request #670
Opened 2024-04-09 19:01 UTC by danieljcafonso

2024-04-11 01:00 UTC, LadyBluenotes requested changes
Can you please link out to the relevant sections when you're referring to them?

Thank you very much for doing this, too, Daniel!

2024-04-11 01:00 UTC, LadyBluenotes commented on src/routes/solid-meta/reference/meta/title.mdx
> +`Title` is a component that renders the `title` element.
```suggestion
`Title` is a component that renders the `title` element.
This will render the title of the page in the browser tab.
```

2024-04-12 16:21 UTC, LadyBluenotes requested changes

2024-04-12 16:21 UTC, LadyBluenotes commented on src/routes/solid-meta/reference/meta/metaprovider.mdx
> +`MetaProvider` is a parent component responsible for wrapping all your meta components.
```suggestion
`MetaProvider` is a parent component responsible for wrapping all the metadata components.
```

2024-04-15 15:32 UTC, danieljcafonso commented on src/routes/solid-meta/getting-started/installation-and-setup.mdx
> +<div id="yarn">```bash frame="none" yarn add @solidjs/meta ```</div>
it did! fixed!

2024-04-16 22:54 UTC, LadyBluenotes requested changes

2024-04-16 22:54 UTC, LadyBluenotes commented on src/routes/solid-meta/getting-started/installation-and-setup.mdx
> +This process is important for maintaining the expected behavior, such as Single Page Applications (SPAs) when pages load that require changes to the head tags.
Can you link out the package for getAssets?

```suggestion
3.  If using SolidJS on the server with JSX, no additional configuration is required:
```js
import { MetaProvider, Title, Link, Meta } from "@solidjs/meta";

const App = () => (
	<MetaProvider>
		<div class="Home">
			<Title>Title of page</Title>
			<Link rel="canonical" href="http://solidjs.com/" />
			<Meta name="example" content="whatever" />
		</div>
	</MetaProvider>
);
```
On the server, tags are collected, and then on the client, server-generated tags are replaced with those rendered on the client side.
This process is important for maintaining the expected behavior, such as Single Page Applications (SPAs) when pages load that require changes to the head tags.

If you need to manage asset insertion, you can do this using `getAssets` from `solid-js/web`. 

```

2024-04-16 22:54 UTC, LadyBluenotes commented on src/routes/solid-meta/reference/meta/base.mdx
> +`Base` is a component specifies the base URL for all relative URLs in the document.
```suggestion
`Base` is a component that specifies the base URL for all relative URLs in the document.
```

2024-04-16 22:54 UTC, LadyBluenotes commented on src/routes/solid-meta/reference/meta/link.mdx
> +To use an emoji as a favicon. First create function called `emojiSvg`:
```suggestion
To use an emoji as a favicon, first create a function that returns a data URI containing an SVG image:
```

2024-04-16 22:54 UTC, LadyBluenotes commented on src/routes/solid-meta/reference/meta/link.mdx
> +Then, in your Link component href pass the emoji into the `emojiSvg` function.
```suggestion
Following this, include the emoji as an argument within that function in the `href` property of the Link component:
```

2024-04-16 22:54 UTC, LadyBluenotes commented on src/routes/solid-meta/reference/meta/meta.mdx
> +`Meta` tags are considered the same and overridden if `name` attributes match.
```suggestion
```

2024-04-16 22:54 UTC, LadyBluenotes commented on src/routes/solid-meta/reference/meta/meta.mdx
> +
```suggestion


`Meta` components can be placed in the [`MetaProvider`](/solid-meta/reference/meta/metaprovider) or added throughout the application for additional metadata or override parents.
`Meta` tags are considered the same and will be overridden if `name` attributes match.
```

2024-04-23 17:15 UTC, LadyBluenotes approved these changes

2024-04-23 17:15 UTC, merged